version: '3'
services:
   nginx:
      image: nginx:latest
      ports:
         - 8080:80
      volumes:
         - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
         - ./www/html:/var/www/html
      depends_on:
         - php

   php:
      build:
         context: ./php
         dockerfile: ./Dockerfile
      volumes:
         - ./www/html:/var/www/html
      depends_on:
         - db

   db:
      build:
         context: ./mysql
         dockerfile: ./Dockerfile
      ports:
         - 13306:3306
      volumes:
         - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      environment:
         TZ: Asia/Tokyo
         MYSQL_ROOT_PASSWORD: secret

   phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      ports:
         - 8888:80
      depends_on:
         - db

   composer:
      image: composer:2.0
      working_dir: /var/www/html
      volumes:
         - ./www/html:/var/www/html
      command: composer update
